### ISSUE TITLE
mongoc_collection_count() ignores the flags parameter

### ISSUE THREAD

**Issue by mjburghoffer** [mongodb/mongo-c-driver#103]
On line 529 in /src/mongoc/mongoc-collection.c, there is a parameter *mongoc_query_flags_t flags*, but it is not passed to any subsequent functions.  As a result, it is impossible to call this method to get a count of a collection on a secondary read-only slave.

**Comment by samantharitter** [comment]
@mjburghoffer I'm going to close this issue, as there's a workaround and no driver changes to make at this time.  If you're still having problems with this, please open a ticket in [our JIRA project](https://jira.mongodb.org/browse/CDRIVER).  Thank you!
