### ISSUE TITLE
clang warning on osx

### ISSUE THREAD

**Issue by jeroenooms** [mongodb/mongo-c-driver#114]
When compiling on OSX:

	clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -D BSON_COMPILATION -DMONGOC_COMPILATION -I. -Iyajl -Ibson -Imongoc -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c bson/bson-value.c -o bson/bson-value.o
	bson/bson-utf8.c:199:17: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
	         if ((c >= 0x0000) && (c <= 0x007F)) {
	              ~ ^  ~~~~~~
	1 warning generated.

**Comment by samantharitter** [comment]
Hi @jeroenooms, are you still having this issue?
