### ISSUE TITLE
mingw-w64 warnings

### ISSUE THREAD

**Issue by jeroenooms** [mongodb/mongo-c-driver#115]
I get these warnings for `mongoc 1.0.2` with gcc 4.6.3 on mingw-w64 (part of the R project)

	Found the following significant warnings:
	  yajl/yajl_gen.c:205:5: warning: too many arguments for format [-Wformat-extra-args]
	  bson/bson-error.c:111:4: warning: implicit declaration of function 'strerror_s' [-Wimplicit-function-declaration]
	  bson/bson-json.c:542:10: warning: implicit declaration of function 'sscanf_s' [-Wimplicit-function-declaration]

**Comment by samantharitter** [comment]
Hi @jeroenooms, are you still having this issue?
