### ISSUE TITLE
Undined reference "bson_atomic_int64_add" on 32bit embed system

### ISSUE THREAD

**Issue by crossa** [mongodb/mongo-c-driver#135]
I want to port the mongoc_driver to my raspberry pi but there is an issues when I compile the driver under the the raspberry pi with raspbian system.
The  compiler said: Undifined reference "bson_atomic_int64_add".
The raspberry pi only support 32 bit  system and I have installed a raspbian system with gcc and g++ for it.

I have tried to use the cross toolchain to build the driver and it has been done without errors.
But I think there is some difference because the os of the host is  a 64bit system and the 'bson_atomic_int64_add' was supported.

I prefer the mongoc driver than mongoc++ driver because I didn't want  to install boost library for raspbian. 

Can any body tell me how to fixed the issue?
I hope the mongoc driver can be compiled under raspbian system.

**Comment by samantharitter** [comment]
Hi @crossa, I've opened a [JIRA ticket for this issue](https://jira.mongodb.org/browse/CDRIVER-515), we'll address it from there.  Thank you!
