### ISSUE TITLE
undefined reference to `bson_atomic_int64_add' (mongo-c-driver-1.1.0) in armv7l

### ISSUE THREAD

**Issue by nadolny** [mongodb/mongo-c-driver#139]
Compile with:

Linux 3.4.75+ #6 PREEMPT Wed Mar 19 13:53:29 EET 2014 armv7l GNU/Linux

$ gcc --versiongcc (Debian 4.6.3-14) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

../mongoDB_C_Driver/mongo-c-driver-1.1.0
$ ./configure
     This is an unstable version of libmongoc.
	 It is for test purposes only.

	 Please, DO NOT use it in a production environment.
	 It will probably crash and you will lose your data.

	 Additionally, the API/ABI may change during the course
	 of development.

	 Thanks,

	   The libmongoc team.

	 *** END OF WARNING ***

	libmongoc was configured with the following options:

	Build configuration:
	  Enable debugging (slow)                          : no
	  Compile with debug symbols (slow)                : no
	  Enable GCC build optimization                    : yes
	  Enable automatic binary hardening                : yes
	  Code coverage support                            : no
	  Cross Compiling                                  : no
	  Fast counters                                    : no
	  SASL                                             : no
	  SSL                                              : yes
	  Libbson                                          : system

	Documentation:
	  man                                              : no
	  HTML                                             : no

$ make
  ...
  CC       src/mongoc/libmongoc_1_0_la-mongoc-scram.lo
  CC       src/mongoc/libmongoc_1_0_la-mongoc-stream-tls.lo
  CC       src/mongoc/libmongoc_1_0_la-mongoc-ssl.lo
  CCLD     libmongoc-1.0.la
  CC       src/tools/mongoc_stat-mongoc-stat.o
src/tools/mongoc-stat.c: In function âmongoc_counters_print_infoâ:
src/tools/mongoc-stat.c:184:15: warning: cast increases required alignment of target type [-Wcast-align]
  CCLD     mongoc-stat
  CC       tests/test_load-test-load.o
  CC       tests/test_load-mongoc-tests.o
  CCLD     test-load
./.libs/libmongoc-priv.so: undefined reference to `bson_atomic_int64_add'
collect2: ld returned 1 exit status
make[1]: *** [test-load] Error 1
make[1]: Leaving directory `/home/prjsprod/install/mongoDB_C_Driver/mongo-c-driver-1.1.0'
make: *** [all-recursive] Error 1

My best regards to all the menbers mongo-c-driver.

**Comment by samantharitter** [comment]
Hi @nadolny, I've opened a [ticket for this issue in our JIRA project](https://jira.mongodb.org/browse/CDRIVER-514), we'll address it from there for tracking purposes.  Thanks!
