### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by alexeyvo** [mongodb/mongo-c-driver#154]
Documentation pages missing for some API's:
* mongoc_gridfs_file_remove
* mongoc_gridfs_remove_by_filename
* mongoc_database_find_collections

**Comment by samantharitter** [comment]
Hi @alexeyvo, I've opened a [ticket for this issue in our JIRA project](https://jira.mongodb.org/browse/CDRIVER-513), we'll look at it from there.  Thanks!
