### ISSUE TITLE
how to use gridfs  read from secondary node?

### ISSUE THREAD

**Issue by bjddh** [mongodb/mongo-c-driver#156]
......
   read_prefs = mongoc_read_prefs_new(MONGOC_READ_SECONDARY);
   mongoc_client_set_read_prefs(client, read_prefs);
.....
   gridfs = mongoc_client_get_gridfs (client, "test", "fs", &error);
....   
mongoc_gridfs_find_one_by_filename(gridfs, filename, &error);

gridfs would create "filename" index everytime 

and it can not link to secondary at all.

use same config, bson object can read from seconday node.

PS:   c++, csharp,python gridfs can read from secondary node

**Comment by bjddh** [comment]
read mode add when link chunks&files
==========================================================
mongoc-gridfs.c

Line120:
   bson_snprintf (buf, sizeof(buf), "%s.chunks", prefix);
   //gridfs->chunks = _mongoc_collection_new (client, db, buf, NULL, NULL);   
   gridfs->chunks = _mongoc_collection_new (client, db, buf, client->read_prefs, NULL);

   bson_snprintf (buf, sizeof(buf), "%s.files", prefix);
// gridfs->files = _mongoc_collection_new (client, db, buf, NULL, NULL);
   gridfs->files = _mongoc_collection_new (client, db, buf, client->read_prefs, NULL);

**Comment by samantharitter** [comment]
Hi @bjddh, I've opened a [JIRA ticket for this issue](https://jira.mongodb.org/browse/CDRIVER-512), we'll address it there for tracking purposes.  Thanks!
