### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by jeromelebel** [mongodb/mongo-c-driver#163]
Those 3 functions can't be static and non static at the same time. 

int b64_ntop (uint8_t const *src, size_t srclength, char *target, size_t targsize);
void b64_initialize_rmap (void);
int b64_pton (char const *src, uint8_t *target, size_t targsize);

https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-b64-private.h#L29
https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-b64-private.h#L35
https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-b64-private.h#L38

https://github.com/mongodb/libbson/blob/master/src/bson/b64_ntop.h#L116
https://github.com/mongodb/libbson/blob/master/src/bson/b64_pton.h#L132
https://github.com/mongodb/libbson/blob/master/src/bson/b64_pton.h#L161

Please choose which one you prefer.

By the way, you have 2 definitions of Assert(), Base64 and Pad64 (one in b64_ntop.h and one in b64_pton.h). It would be better to put them in the same file.

**Comment by samantharitter** [comment]
Hi @jeromelebel, I've opened a [JIRA ticket for this issue](https://jira.mongodb.org/browse/CDRIVER-508), we'll address this from there for tracking purposes.  Thanks!
