### ISSUE TITLE
Cannot append to file

### ISSUE THREAD

**Issue by amy-arthur** [mongodb/mongo-c-driver#56]
Because the line 721 in mongoc-gridfs-file.c:
    BSON_ASSERT(file->length > (int64_t)offset);
Application cannot seek to the end of the file that means cannot append to file. The correct statement may be >=:
    BSON_ASSERT(file->length >= (int64_t)offset);

**Comment by samantharitter** [comment]
Appending to files is not a feature supported by GridFS.  If you wish to alter a file once it's in GridFS, you'll have to read it from the system, make any necessary changes or additions, and write it to GridFS anew.  We cannot safely support appending to files at this time.

I'm going to close this issue, if you have any other questions or concerns regarding GridFS, please open a ticket on [our JIRA project](https://jira.mongodb.org/browse/CDRIVER).  Thank you!
