### ISSUE TITLE
Bulk insert : No healthy connection, Failure to buffer 4 bytes

### ISSUE THREAD

**Issue by blue112** [mongodb/mongo-c-driver#57]
I'm trying to insert some data into my single-node mongodb cluster. I'm inserting into two connections at once, and I'm using two separated `mongoc_bulk_operation_t` objects to add inserts into them.

Most of the time, few of my objects are inserted (about 10%), and this error triggers when I use `mongoc_bulk_operation_execute` :
> 2014/07/01 12:01:04.0706: [14879]:  WARNING:       stream: Failure to buffer 4 bytes:  Failed to buffer 4 bytes within 300000 milliseconds.
> { "nInserted" : 10449, "nMatched" : 0, "nRemoved" : 0, "nUpserted" : 0, "writeErrors" : [  ] }
> Error: No healthy connections.

I can't find any resource about this error on the internet, except the code in the repository.

**Comment by samantharitter** [comment]
@blue112 is this still an issue for you?
