### ISSUE TITLE
fails to build on CentOS 6.5 with autoconf <  2.65

### ISSUE THREAD

**Issue by bauman** [mongodb/mongo-c-driver#61]
mongo-c-driver.spec

The most recent driver I can build on CentOS 6.5 is 0.94.2

[dan@office ~]$ rpmbuild -ba rpmbuild/SPECS/mongo-c-driver.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Zukauw
+ umask 022
+ cd /home/dan/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /home/dan/rpmbuild/BUILD
+ rm -rf mongo-c-driver-0.98.0
+ /usr/bin/gzip -dc /home/dan/rpmbuild/SOURCES/mongo-c-driver-0.98.0.tar.gz
+ /bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd mongo-c-driver-0.98.0
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ automake
aclocal.m4:17: warning: this file was generated for autoconf 2.69.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
configure.ac:44: error: Autoconf version 2.65 or higher is required
aclocal.m4:432: AM_INIT_AUTOMAKE is expanded from...
configure.ac:44: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
automake: autoconf failed with exit status: 63
error: Bad exit status from /var/tmp/rpm-tmp.Zukauw (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Zukauw (%prep)

[root@office dan]# yum install autoconf
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
 * base: mirror.itc.virginia.edu
 * epel: mirrors.einstein.yu.edu
 * extras: mirror.thelinuxfix.com
 * updates: mirror.sanctuaryhost.com
Setting up Install Process
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Nothing to do

**Comment by samantharitter** [comment]
@bauman I'm going to close this issue, if this becomes a problem for you again please open a ticket in [our JIRA project](https://jira.mongodb.org/browse/CDRIVER).  Thanks!
